### ISSUE TITLE
Json breaking while receiving response

### ISSUE THREAD

**Issue by ktilakraj** [neilco/EventSource#9]
When I am trying to access the event source , I am getting the json breaking or not receiving proper json.

**Comment by neilco** [comment]
Can you provide an example?

**Comment by vishalnmahajan** [comment]
The response received is broken sometimes and is delivered in 2 separate chunks where as sometimes a complete chunk of response is received. There is no major difference in the payload, but this happens intermittently.

The broken response:
{
 "gamecode": "179569",
 "type": "commentary",
 "filename": "star$179569_commentary_recent_1.json",
 "content": {
   "Commentary": [
     {
       "Over": "98.2",
       "Id": "688",
       "Runs": "0",
       "Detail": "",
       "Isball": true,
       "Bowler": "4321",
       "Batsman": "24815",
       "Commentary": "No run."
     },
     {
       "Over": "98.1",
       "Id": "687",
       "Runs": "0",
       "Detail": "",
       "Isball": true,
       "Bowler": "4321",
       "Batsman": "24815",
       "Commentary": "Good length ball around off, shaping away, Yasir feels for it and gets beaten."
     },
     {
       "Summary": {
         "Score": "333/9",
         "Over": "98",
         "Runs": "3",
         "Wickets": "0",
         "Batsmen": [
           {
             "Batsman": "7768",
             "Isonstrike": true,
             "Runs": "12",
             "Balls": "8",
             "Fours": "3",
             "Sixes": "0"
           },
           {
             "Batsman": "24815",
             "Runs": "5",
             "Balls": "7",
             "Fours": "0",
             "Sixes": "0"
           }
         ],
         "Bowlers": [
           {
             "Bowler": "3840",
             "Overs": "27",
             "Maidens": "9",
             "Runs": "70",
             "Wickets": "2"
           }
         ]
       },
       "Over": "97.6",
       "Id": "686",
       "Runs": "0",
       "Detail": "",
       "Isball": true,
       "Bowler": "3840",
       "Batsman": "7768",
       "Commentary": "Shows the full face of the bat and defends the ball off the back foot."
     },
     {
       "Over": "97.5",
       "Id": "685",
       "Runs": "3",
       "Detail": "",
       "Isball": true,
       "Bowler": "3840",
       "Batsman": "24815",
       "Commentary": "Lovely shot! Full length ball angling into the batsman, Shah gets forward and nicely drives it through mid on for three runs. Strokemaking tailenders at work for Pakistan!"
     },
     {
       "Over": "",
       "Id": "684",
       "Runs": "",
       "Detail": "",
       "Isball": false,
       "Bowler": "",
       "Batsman": "",
       "Embed": {
         "type": "tweet",
         "id": "753904726685736960",
         "code": "<blockquote class=\"twitter-tweet\" data-lang=\"en\"><p lang=\"en\" dir=\"ltr\">Great stuff from a top bowler and even better man <a href=\"https://twitter.com/chriswoakes\">@chriswoakes</a> <a href=\"https://twitter.com/hashtag/impressive?src=hash\">#impressive</a></p>— Nick Compton (@thecompdog) <a href=\"https://twitter.com/thecompdog/status/753904726685736960\">July 15, 2016</a></blockquote>"
       },
       "Commentary": "Tweet...."

Next set of response:
},
     {
       "Over": "97.4",
       "Id": "683",
       "Runs": "0",
       "Detail": "",
       "Isball": true,
       "Bowler": "3840",
       "Batsman": "24815",
       "Commentary": "Bouncer again and Shah ducks underneath it."
     },
     {
       "Over": "97.3",
       "Id": "682",
       "Runs": "0",
       "Detail": "",
       "Isball": true,
       "Bowler": "3840",
       "Batsman": "24815",
       "Commentary": "Angles in a full ball on middle, Yasir pushes it off his pads to mid on."
     },
     {
       "Over": "97.2",
       "Id": "681",
       "Runs": "0",
       "Detail": "",
       "Isball": true,
       "Bowler": "3840",
       "Batsman": "24815",
       "Commentary": "Bowls it on a length and outside off, Yasir flashes and misses. No footwork as expected from a number 11 batsman."
     },
     {
       "Over": "97.1",
       "Id": "680",
       "Runs": "0",
       "Detail": "",
       "Isball": true,
       "Bowler": "3840",
       "Batsman": "24815",
       "Commentary": "Bouncer, down the leg side, an easy leave for Yasir."
     },
     {
       "Over": "",
       "Id": "679",
       "Runs": "",
       "Detail": "",
       "Isball": false,
       "Bowler": "",
       "Batsman": "",
       "Embed": {
         "type": "tweet",
         "id": "753903680982769664",
         "code": "<blockquote class=\"twitter-tweet\" data-lang=\"en\"><p lang=\"en\" dir=\"ltr\">What a shot from Brian Charles Amir.</p>— Ahmed (@azkhawaja1) <a href=\"https://twitter.com/azkhawaja1/status/753903680982769664\">July 15, 2016</a></blockquote>"
       },
       "Commentary": "Tweet...."
     }
   ]
 }
}

**Comment by neilco** [comment]
If you're sending large chunks of data in each event, you can span the lines over multiple consecutive `data` fields, like so:

```yaml
event: new_updates
data: {
data:  "gamecode": "179569",
data:  "type": "commentary",
data:  "filename": "star$179569_commentary_recent_1.json",
data:  "content": {
data:    "Commentary": [
data:      {
data:        "Over": "98.2",
data:        "Id": "688",
data:        "Runs": "0",
data:        "Detail": "",
data:        "Isball": true,
data:        "Bowler": "4321",
data:        "Batsman": "24815",
data:        "Commentary": "No run."
data:      },
data:      {
data:        "Over": "98.1",
data:        "Id": "687",
data:        "Runs": "0",
data:        "Detail": "",
data:        "Isball": true,
data:        "Bowler": "4321",
data:        "Batsman": "24815",
data:        "Commentary": "Good length ball around off, shaping away, Yasir feels for it and gets beaten."
data:      },
data:      {
data:        "Summary": {
data:          "Score": "333/9",
data:          "Over": "98",
data:          "Runs": "3",
data:          "Wickets": "0",
data:          "Batsmen": [
data:            {
data:              "Batsman": "7768",
data:              "Isonstrike": true,
data:              "Runs": "12",
data:              "Balls": "8",
data:              "Fours": "3",
data:              "Sixes": "0"
data:            },
data:            {
data:              "Batsman": "24815",
data:              "Runs": "5",
data:              "Balls": "7",
data:              "Fours": "0",
data:              "Sixes": "0"
data:            }
data:          ],
data:          "Bowlers": [
data:            {
data:              "Bowler": "3840",
data:              "Overs": "27",
data:              "Maidens": "9",
data:              "Runs": "70",
data:              "Wickets": "2"
data:            }
data:          ]
data:        },
data:        "Over": "97.6",
data:        "Id": "686",
data:        "Runs": "0",
data:        "Detail": "",
data:        "Isball": true,
data:        "Bowler": "3840",
data:        "Batsman": "7768",
data:        "Commentary": "Shows the full face of the bat and defends the ball off the back foot."
data:      },
data:      {
data:        "Over": "97.5",
data:        "Id": "685",
data:        "Runs": "3",
data:        "Detail": "",
data:        "Isball": true,
data:        "Bowler": "3840",
data:        "Batsman": "24815",
data:        "Commentary": "Lovely shot! Full length ball angling into the batsman, Shah gets forward and nicely drives it through mid on for three runs. Strokemaking tailenders at work for Pakistan!"
data:      },
data:      {
data:        "Over": "",
data:        "Id": "684",
data:        "Runs": "",
data:        "Detail": "",
data:        "Isball": false,
data:        "Bowler": "",
data:        "Batsman": "",
data:        "Embed": {
data:          "type": "tweet",
data:          "id": "753904726685736960",
data:          "code": "<blockquote class=\"twitter-tweet\" data-lang=\"en\"><p lang=\"en\" dir=\"ltr\">Great stuff from a top bowler and even better man <a href=\"https://twitter.com/chriswoakes\">@chriswoakes</a> <a href=\"https://twitter.com/hashtag/impressive?src=hash\">#impressive</a></p>— Nick Compton (@thecompdog) <a href=\"https://twitter.com/thecompdog/status/753904726685736960\">July 15, 2016</a></blockquote>"
data:        },
data:        "Commentary": "Tweet...."
data:      },
data:      {
data:        "Over": "97.4",
data:        "Id": "683",
data:        "Runs": "0",
data:        "Detail": "",
data:        "Isball": true,
data:        "Bowler": "3840",
data:        "Batsman": "24815",
data:        "Commentary": "Bouncer again and Shah ducks underneath it."
data:      },
data:      {
data:        "Over": "97.3",
data:        "Id": "682",
data:        "Runs": "0",
data:        "Detail": "",
data:        "Isball": true,
data:        "Bowler": "3840",
data:        "Batsman": "24815",
data:        "Commentary": "Angles in a full ball on middle, Yasir pushes it off his pads to mid on."
data:      },
data:      {
data:        "Over": "97.2",
data:        "Id": "681",
data:        "Runs": "0",
data:        "Detail": "",
data:        "Isball": true,
data:        "Bowler": "3840",
data:        "Batsman": "24815",
data:        "Commentary": "Bowls it on a length and outside off, Yasir flashes and misses. No footwork as expected from a number 11 batsman."
data:      },
data:      {
data:        "Over": "97.1",
data:        "Id": "680",
data:        "Runs": "0",
data:        "Detail": "",
data:        "Isball": true,
data:        "Bowler": "3840",
data:        "Batsman": "24815",
data:        "Commentary": "Bouncer, down the leg side, an easy leave for Yasir."
data:      },
data:      {
data:        "Over": "",
data:        "Id": "679",
data:        "Runs": "",
data:        "Detail": "",
data:        "Isball": false,
data:        "Bowler": "",
data:        "Batsman": "",
data:        "Embed": {
data:          "type": "tweet",
data:          "id": "753903680982769664",
data:          "code": "<blockquote class=\"twitter-tweet\" data-lang=\"en\"><p lang=\"en\" dir=\"ltr\">What a shot from Brian Charles Amir.</p>— Ahmed (@azkhawaja1) <a href=\"https://twitter.com/azkhawaja1/status/753903680982769664\">July 15, 2016</a></blockquote>"
data:        },
data:        "Commentary": "Tweet...."
data:      }
data:    ]
data:  }
data: }
```
